### ISSUE TITLE
statx() requires Docker 18.04+

### ISSUE THREAD

**Issue by daniviga** [gem/oq-qgis-server#1]
Qt 5.10+ use `statx()` syscalls that are not allowed in unprivileged Docker containers running Docker < 18.04.

Refs:
- https://bugzilla.redhat.com/show_bug.cgi?id=1593842
- https://github.com/moby/moby/pull/36417

**Comment by daniviga** [comment]
On Fedora the issue can be workaround either:
- Installing [Docker CE from Docker](https://docs.docker.com/install/linux/docker-ce/fedora/)
- Install `moby-engine` from Fedora repositories: `sudo dnf install moby-engine`

**Comment by mbernasocchi** [comment]
also note that docker 18.04+ alone is not enough, the host must also have at least libseccomp2_2.3.3 which is not the case for ubuntu 18.04.1 (it has libseccomp2_2.3.1)
`dpkg -i libseccomp2_2.3.3-3ubuntu1_amd64.deb` solves this on ubuntu 18.04.1

**Comment by mbernasocchi** [comment]
the docker-ce repo does unfortunately _not_ have libseccomp

**Comment by daniviga** [comment]
Added https://github.com/gem/oq-qgis-server/blob/master/README.md#requisites

**Comment by daniviga** [comment]
We are now providing also containers based on Ubuntu with an older version of Qt.

We'll see in the future if remove Fedora and use just Ubuntu or whatever.

**Comment by daniviga** [comment]
> also note that docker-ce 18.04+ alone is not enough, the host must also have at least libseccomp2_2.3.3 which is not the case for ubuntu 18.04.1 (it has libseccomp2_2.3.1)
> `dpkg -i libseccomp2_2.3.3-3ubuntu1_amd64.deb` and restarting docker solves this on ubuntu 18.04.1

18.04 now ships `libseccomp 2.4.1-0ubuntu0.18.04.2` which addresses the issue
