### ISSUE TITLE
Add the possibility to map a local font folder

### ISSUE THREAD

**Issue by daniviga** [gem/oq-qgis-server#10]
This allows QGIS server to use custom fonts for the internal rendering

**Comment by lucamanga** [comment]
For me it was sufficient to pass this parameter:

`docker run -d -p 8380:80 --volume=/usr/local/share/fonts:/usr/local/share/fonts ...`

in which the local `/usr/local/share/fonts` contains all the needed fonts.

**Comment by daniviga** [comment]
Yeah, it's a matter only of documenting it and make sure that font cache is up-to-date.

See https://github.com/gem/oq-qgis-server/commit/9221c2976695d7ce327c83fb24bd09327ba517d7

**Comment by daniviga** [comment]
Closed via https://github.com/gem/oq-qgis-server/pull/14
