### ISSUE TITLE
Library missing

### ISSUE THREAD

**Issue by skryptus** [gem/oq-qgis-server#15]
Hello,

I've tried to use your 3.4.5 and 3.6 versions of the Docker, and on both I've found the following error:

/usr/libexec/qgis/qgis_mapserv.fcgi: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

**Comment by daniviga** [comment]
Hi, which version of Docker are you using? On which OS?

**Comment by skryptus** [comment]
I'm using Docker Desktop Community Version 2.0.0.2 (30215), on Windows 10.

**Comment by daniviga** [comment]
> I'm using Docker Desktop Community Version 2.0.0.2 (30215), on Windows 10.

It looks like a platform specific issue (builds are tested via Travis, so the container is fine, but it's tested on Linux only). I don't have any Docker instance on Windows right now. I'll see what I can do.
