### ISSUE TITLE
is QGIS_USER useless?

### ISSUE THREAD

**Issue by lucamanga** [gem/oq-qgis-server#23]
Hi, I tried to start the container:

`docker run [...] -e QGIS_USER=gis openquake/qgis-server:ltr `

but in the log I found this error:

`spawn-fcgi: can't find user name gis`

what is wrong?

**Comment by daniviga** [comment]
You must provide the corresponding id of the user (i.e. via `$(id -u)). the `qgis` user cannot be mapped to an id since is not known by the container internally.

I will improve the README to explain this better.

**Comment by daniviga** [comment]
> I will improve the README to explain this better.

Done in https://github.com/gem/oq-qgis-server/commit/a6c5fd531a535edad0fc92bacbdd0c0a5225b6d0
