### ISSUE TITLE
Custom SVG symbols path

### ISSUE THREAD

**Issue by lucamanga** [gem/oq-qgis-server#24]
Hi, one thing is missing: custom SVG symbols path.

They are usually stored in the QGIS default profile; so I pass the `--profiles-path` parameter to qgis
I don't know how is this possible in actual FCGI version... any idea?

**Comment by daniviga** [comment]
That's a good point. I'll check and report you back.

**Comment by daniviga** [comment]
> I don't know how is this possible in actual FCGI version... any idea?

It is possible: you need to map a volume (or a host folder) to `/var/lib/qgis/.local/share/QGIS/QGIS3/profiles/default/svg/`:

`-v $(pwd):/var/lib/qgis/.local/share/QGIS/QGIS3/profiles/default/svg/`
