### ISSUE TITLE
Impossible to use SVG images (also with those provided by qgis)?

### ISSUE THREAD

**Issue by lucamanga** [gem/oq-qgis-server#25]
Hi, I discovered that I cannot use SVG symbols (the official ones). They are replaced by "?" 
Is there any way to use them?

**Comment by daniviga** [comment]
Issue confirmed: QGIS is catching the wrong path:

```
12:27:18 INFO Server[29]: SVG PATHS: /usr/share/qgis/svg///var/lib/qgis/.local/share/QGIS/QGIS3/profiles/default/svg/
```
instead of `/usr/share/qgis/svg`

**Comment by daniviga** [comment]
> Issue confirmed: QGIS is catching the wrong path:

only the debug log is wrong (it uses `/` as path separator) (https://github.com/qgis/QGIS/pull/9931).
SVGs are working properly for me: could you please provide more debug information? (Like a sample project and the log from `docker logs <container>, after setting `QGIS_SERVER_LOG_LEVEL=0` in the env)

![Screenshot from 2019-05-06 14-57-43](https://user-images.githubusercontent.com/1818657/57226690-dad93880-700f-11e9-97af-404ab3af5f4a.png)

**Comment by daniviga** [comment]
No reply, closing
