### ISSUE TITLE
Rbuild 3.6 including #29

### ISSUE THREAD

**Issue by mbernasocchi** [gem/oq-qgis-server#30]
@daniviga would it be possible to release a version on hub that includes #29? it would be a great help for deploying together with https://github.com/opengisch/docker-lizmap

**Comment by daniviga** [comment]
Would it be 3.8 ok too? `3.8` and `3.8-ubuntu` have been just pushed to Docker Hub.

**Comment by mbernasocchi** [comment]
ok, Ill try those thanks :) 3.4.9 also has it I guess?
cheers
Marco

**Comment by daniviga** [comment]
Of corse, 3.4.9 containers have been pushed too :)
